[package]
name = "zcatr"
version = "0.1.0"
edition = "2021"

[dependencies]
bzip2 = "0.5.0"
clap = { version = "4.5.28", features = ["derive"] }
flate2 = "1.0.35"
infer = "0.19.0"
tar = "0.4.43"
zip = "2.2.2"

